name: Build Stacer Application

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build App
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
        include:
          - os: ubuntu-24.04
            codename: "noble"
          - os: ubuntu-22.04
            codename: "jammy"
          - os: ubuntu-20.04
            codename: "focal"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.4.2
          host: linux
          target: desktop
          arch: gcc_64
          modules: qtcharts

      - name: Install libraries
        run: |
          sudo apt-get install libfuse2

      - name: Install build tools
        run: |
          sudo apt-get install -y dh-make devscripts build-essential lintian

      - name: Build and make release
        run: |
          bash ${{ github.workspace }}/release.sh deb

      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stacer-${{ matrix.codename }}
          path: |
            ${{ github.workspace }}/release/stacer_*.deb
            ${{ github.workspace }}/release/Stacer-*.AppImage

      - name: Publish PPA package
        uses: yuezk/publish-ppa-package@main
        if: matrix.codename == 'noble'
        with:
          tarball: ${{ github.workspace }}/release/stacer_*.orig.tar.xz
          debian_dir: ${{ github.workspace }}/debian/
          repository: "quentiumyt/stacer"
          deb_email: "pro@quentium.fr"
          deb_fullname: "Quentin Lienhardt"
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
          # flatten matrix codenames to a single string
          series: "noble jammy focal"
          new_version_template: "{VERSION}-3"
